"""empty message

Revision ID: 3558491eb7b5
Revises: 6cad98f763bc
Create Date: 2024-08-13 18:23:00.038183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3558491eb7b5'
down_revision = '6cad98f763bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('comments_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_comments_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('likes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_likes_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('posts_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_posts_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('token_block_list_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.String(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('likes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_author_id_fkey', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('likes_author_id_fkey', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key('comments_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_end_transaction_id'))

    op.drop_table('users_version', schema='public')
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_jti'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'))

    op.drop_table('token_block_list_version', schema='public')
    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_posts_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_end_transaction_id'))

    op.drop_table('posts_version', schema='public')
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_likes_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_end_transaction_id'))

    op.drop_table('likes_version', schema='public')
    with op.batch_alter_table('comments_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_comments_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_end_transaction_id'))

    op.drop_table('comments_version', schema='public')
    # ### end Alembic commands ###
